default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bot_backend_development
  username: postgres
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: bot_backend_test
  username: postgres
  password:
  host: localhost
  port: 5432

production:
  primary:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
    port: 5432

  cache:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
    port: 5432

  queue:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
    port: 5432

  cable:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
    port: 5432